# Generated by Django 3.0.2 on 2020-01-22 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabelUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('note_text', models.TextField(blank=True)),
                ('note_image', models.URLField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('delete_time_left', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('collaborators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, to='FundooNotes.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NoteUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
