# Generated by Django 3.0.2 on 2020-01-23 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FundooNotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='delete_time_left',
        ),
        migrations.AlterField(
            model_name='note',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
