# Generated by Django 3.0.2 on 2020-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundooNotes', '0002_auto_20200123_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
