# Generated by Django 3.0.2 on 2020-01-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundooNotes', '0004_auto_20200123_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
