# Generated by Django 3.0.2 on 2020-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundooNotes', '0005_auto_20200124_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
