# Generated by Django 3.0.2 on 2020-03-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundooNotes', '0006_auto_20200124_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
