# Generated by Django 3.0.2 on 2020-03-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundooNotes', '0009_label_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='is_checked',
        ),
    ]
