from .base import *

# Setting up Secret Key
SECRET_KEY = SECRET_KEY

# Setting Up mailing Services
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT

DEBUG = DEBUG

INSTALLED_APPS = INSTALLED_APPS

MIDDLEWARE = MIDDLEWARE

ROOT_URLCONF = ROOT_URLCONF

TEMPLATES = TEMPLATES

WSGI_APPLICATION = WSGI_APPLICATION

DATABASES = DATABASES

AUTH_USER_MODEL = AUTH_USER_MODEL

REST_FRAMEWORK = REST_FRAMEWORK

SWAGGER_SETTINGS = SWAGGER_SETTINGS

LANGUAGE_CODE = LANGUAGE_CODE


TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATIC_URL = '../static/'
