# Generated by Django 2.1 on 2019-12-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confrim_password',
            new_name='confirm_password',
        ),
    ]
